---
abstract: 'Fast and featureful UNIX-style path parsing and manipulation'
author:
  - 'Robert Krimen <robertkrimen@gmail.com>'
build_requires:
  Test::Lazy: 0
  Test::More: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Path-Abstract
recommends:
  Path::Class: 0
requires:
  Carp: 0
  Scalar::Util: 0
  Sub::Exporter: 0
version: 0.096
