---
abstract: 'A fast and featureful class for UNIX-style path manipulation'
author:
  - 'Robert Krimen, C<< <rkrimen at cpan.org> >>'
build_requires:
  Test::Lazy: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.710'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Path-Abstract
no_index:
  directory:
    - inc
    - t
recommends:
  Path::Class: 0
requires:
  Carp: 0
  Scalar::Util: 0
  Sub::Exporter: 0
version: 0.081
